FROM lsiobase/alpine.armhf

# environment settings
ENV HOME="/config" \
    XDG_CONFIG_HOME="/config" \
    XDG_DATA_HOME="/config"

RUN echo "**** install runtime packages ****" && \
    apk add --no-cache \
	privoxy

RUN echo "**** cleanup ****" && \
    rm -rf \
	    /tmp/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 8118
VOLUME /config