dist: trusty
sudo: required

services:
  - docker

language: generic

env:
- ARCH=arm32v7
- ARCH=x86_64

matrix:
  include:
    # - env: TARGET=armv7-unknown-linux-gnueabihf ARCH=arm32v7
    - env: TARGET=x86_64-unknown-linux-gnu ARCH=x86_64

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd baseimage
      - docker build -t $DOCKER_USERNAME/baseimage -f ./Dockerfile_$ARCH . ;
      - docker images
      - docker push $DOCKER_USERNAME/baseimage:$ARCH