dist: trusty
sudo: required

services:
  - docker

language: generic

env:
# - ARCH=x86_64
- ARCH=armv7

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd baseimage
  - if [ $ARCH == "armv7" ]
      curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz
      tar xzf qemu-arm-static.tar.gz
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
    fi
  - docker build -t $DOCKER_USERNAME/baseimage -f ./Dockerfile_$ARCH . ;
  - docker images
  - docker tag $DOCKER_USERNAME/baseimage $DOCKER_USERNAME/baseimage:$ARCH
  - docker push $DOCKER_USERNAME/baseimage:$ARCH