dist: trusty
sudo: required

services:
  - docker

language: generic

env:
# - IMAGE=alpine-baseimage ARCH=x86_64
# - IMAGE=alpine-baseimage ARCH=armv7
# - IMAGE=alpine-privoxy ARCH=x86_64
# - IMAGE=alpine-privoxy ARCH=armv7
# - IMAGE=alpine-qbittorrent ARCH=x86_64
- IMAGE=alpine-qbittorrent ARCH=armv7
# - IMAGE=ubuntu-baseimage ARCH=x86_64

script:
  - cd $IMAGE
  - ./build.sh