dist: trusty
sudo: required

services:
  - docker

language: generic

env:
# - ARCH=x86_64
- ARCH=armv7

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd alpine-baseimage
  # Install build deps
  - if [ $ARCH == "armv7" ] ;
      then curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz;
      tar xzf qemu-arm-static.tar.gz;
      docker run --rm --privileged multiarch/qemu-user-static:register --reset;
      chmod +x build/*;
      build/minirootfs-download.sh;
    fi;
  # Build image
  - docker build -t $DOCKER_USERNAME/alpine-baseimage -f ./Dockerfile_$ARCH . ;
  # Tag image and upload to Dockerhub
  - docker images
  - docker tag $DOCKER_USERNAME/alpine-baseimage $DOCKER_USERNAME/alpine-baseimage:$ARCH
  - docker push $DOCKER_USERNAME/alpine-baseimage:$ARCH