FROM lsiobase/alpine

# environment settings
ENV HOME="/config" \
    XDG_CONFIG_HOME="/config" \
    XDG_DATA_HOME="/config" \
    FLOWS=flows.json \
    NODE_PATH=/usr/src/node-red/node_modules:/config/node_modules

RUN echo "**** install runtime packages ****" && \
    apk update && \
    apk add --no-cache \
	dbus \
        nodejs \
        npm \
        avahi \
        avahi-compat-libdns_sd \
        avahi-dev

RUN echo "**** install build packages ****" && \
    apk add --no-cache --virtual build-dependencies \
        build-base \
        gcc \
        wget \
        git \
        make \
        libtool \
        autoconf \
        automake

# add local files
COPY root/ /

RUN echo "**** install node packages ****" && \
    npm install --prefix /usr/src/node-red

RUN echo "**** remove build dependencies ****" && \
    apk del build-dependencies

RUN echo "**** cleanup ****" && \
    rm -rf \
	    /tmp/*

# ports and volumes
EXPOSE 1880
VOLUME /config
