FROM arm32v7/ubuntu:16.04

COPY qemu-arm-static /usr/bin/qemu-arm-static

COPY . /bd_build

RUN /bd_build/prepare.sh && \
	/bd_build/system_services.sh && \
	/bd_build/utilities.sh && \
	/bd_build/cleanup.sh

# Add USER
RUN useradd --no-create-home --uid $UID $USER

CMD ["/sbin/my_init"]
