FROM lsiobase/alpine:3.8

# set version label
ARG BUILD_DATE
ARG VERSION

# environment settings
ENV NEXTCLOUD_PATH="/config/www/nextcloud"

# install packages
# RUN echo "**** install build packages ****" && \
#   apk add --no-cache --virtual=build-dependencies \
#     autoconf \
#     automake \
#     file \
#     g++ \
#     gcc \
#     make \
#     php7-dev \
#     re2c \
#     samba-dev \
#     zlib-dev

RUN echo "**** install runtime packages ****" && \
  apk add --no-cache \
    apache2-utils \
    curl \
    ffmpeg \
    git \
    imagemagick \
    libressl2.7-libssl \
    libxml2 \
    logrotate \
    nano \
    nginx \
    openssl \
    php7 \
    php7-apcu \
    php7-bz2 \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-exif \
    php7-fileinfo \
    php7-fpm \
    php7-ftp \
    php7-gd \
    php7-gmp \
    php7-iconv \
    php7-imagick \
    php7-imap \
    php7-intl \
    php7-json \
    php7-ldap \
    php7-mbstring \
    php7-mcrypt \
    php7-memcached \
    php7-opcache \
    php7-openssl \
    php7-pcntl \
    php7-pdo_mysql \
    php7-pdo_pgsql \
    php7-pdo_sqlite \
    php7-pgsql \
    php7-posix \
    php7-redis \
    php7-session \
    php7-simplexml \
    php7-sqlite3 \
    php7-xml \
    php7-xmlreader \
    php7-xmlwriter \
    php7-zip \
    php7-zlib \
    sudo \
    tar \
    unzip

# configure nginx
RUN echo "**** configure nginx ****" && \
  echo 'fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> \
    /etc/nginx/fastcgi_params && \
  rm -f /etc/nginx/conf.d/default.conf && \
  echo "**** fix logrotate ****" && \
  sed -i "s#/var/log/messages {}.*# #g" /etc/logrotate.conf

RUN echo "**** configure php and nginx for nextcloud ****" && \
  sed -i \
    -e 's/;opcache.enable.*=.*/opcache.enable=1/g' \
    -e 's/;opcache.interned_strings_buffer.*=.*/opcache.interned_strings_buffer=8/g' \
    -e 's/;opcache.max_accelerated_files.*=.*/opcache.max_accelerated_files=10000/g' \
    -e 's/;opcache.memory_consumption.*=.*/opcache.memory_consumption=128/g' \
    -e 's/;opcache.save_comments.*=.*/opcache.save_comments=1/g' \
    -e 's/;opcache.revalidate_freq.*=.*/opcache.revalidate_freq=1/g' \
    -e 's/;always_populate_raw_post_data.*=.*/always_populate_raw_post_data=-1/g' \
    -e 's/memory_limit.*=.*128M/memory_limit=512M/g' \
      /etc/php7/php.ini && \
  sed -i \
    '/opcache.enable=1/a opcache.enable_cli=1' \
      /etc/php7/php.ini && \
  echo "env[PATH] = /usr/local/bin:/usr/bin:/bin" >> /etc/php7/php-fpm.conf

# cleanup
RUN echo "**** cleanup ****" && \
  apk del --purge \
	build-dependencies && \
  rm -rf \
	/tmp/*

# copy local files
COPY root/ /

# ports and volumes
# EXPOSE 443
VOLUME /config /data


